export const FETCH_RELEASES = 'RELEASES/FETCH_RELEASES';
export const FETCH_RELEASES_COMPLETE = 'RELEASES/FETCH_RELEASES_COMPLETE';
export const FETCH_RELEASES_FAILED = 'RELEASES/FETCH_RELEASES_FAILED';

