export const FETCH_RELEASES = 'RELEASES/FETCH_RELEASES';
export const FETCH_RELEASES_COMPLETE = 'RELEASES/FETCH_RELEASES_COMPLETE';
export const FETCH_RELEASES_FAILED = 'RELEASES/FETCH_RELEASES_FAILED';
export const ADD_TO_FAVORITES = 'RELEASES/ADD_TO_FAVORITES';
export const REMOVE_FROM_FAVORITES = 'RELEASES/REMOVE_FROM_FAVORITES';

